[startpage]
cards = [
  { name = "Journals", link = "/journals/",  icon = "fa-book-open"},
  { name = "Software", link = "/software/",	 icon = "fa-code"},
  { name = "People",   link = "/people/",    icon = "fa-user"},
  { name = "Jobs",     link = "/jobs/",      icon = "fa-ad"},
  { name = "Tools",    link = "/tools/",     icon = "fa-tools"},
  { name = "Misc.",    link = "/misc/",      icon = "fa-link"},
]

[edit_page]
repo_url = "https://github.com/seisman/link.seisman.info"
edit_mode = "edit"
repo_dir = "content"
edit_text = "Contribute more links to this page!"
