baseURL = "https://link.seisman.info/"
languageCode = "en-us"
title = "SeisMan's links"

[params]
cards = [
  { name = "Journals",  link = "/journals",  icon = "fa-book-open"},
  { name = "Softwares", link = "/softwares", icon = "fa-code"},
  { name = "People",    link = "/people",    icon = "fa-user"},
  {name = "Jobs",       link = "/jobs",      icon = "fa-ad"},
  {name = "Tools",      link = "/tools",     icon = "fa-tools"},
  {name = "Misc",       link = "/misc",      icon = "fa-link"},
]
